import json
import os

# Paths
BASE_DIR = r"c:\Users\Gustavo\Downloads\neurova"

MINDHAFEN_WORKFLOW = os.path.join(BASE_DIR, "mindhafen", "workflows", "n8n_workflow_PRODUCTION_v2.json")
MINDHAFEN_HTML = os.path.join(BASE_DIR, "mindhafen", "EMAIL_TEMPLATE_MINDHAFEN.html")
MINDHAFEN_OUT = os.path.join(BASE_DIR, "mindhafen", "workflows", "mindhafen_production_v3_html.json")

ARGENTERIO_WORKFLOW = os.path.join(BASE_DIR, "argenterio", "workflow_auditor_v7_FIXED.json")
ARGENTERIO_HTML = os.path.join(BASE_DIR, "argenterio", "EMAIL_TEMPLATE_ARGENTERIO_TEASER.html")
ARGENTERIO_OUT = os.path.join(BASE_DIR, "argenterio", "workflow_auditor_v8_HTML.json")

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4)

def process_mindhafen():
    print("Processing MindHafen...")
    workflow = json.loads(read_file(MINDHAFEN_WORKFLOW))
    html_template = read_file(MINDHAFEN_HTML)

    # Create Code Node
    code_node_js = f"""
    const htmlTemplate = `{html_template}`;
    
    // Variables from previous nodes
    // Using defensive checks
    const body = $('Webhook').item.json.body || {{}};
    const name = body.name || 'Usuario';
    const goal = body.goal || 'Bienestar';
    
    const aiOutput = $('AI Agent - Email Generator').item.json.output || '';
    
    // Simple Replace
    let finalHtml = htmlTemplate.replace('{{{{name}}}}', name);
    finalHtml = finalHtml.replace('{{{{goal}}}}', goal);
    finalHtml = finalHtml.replace('{{{{content}}}}', aiOutput.replace(/\\n/g, '<br>')); // Convert newlines to breaks
    
    return {{
        json: {{
            html: finalHtml
        }}
    }};
    """

    code_node = {
        "parameters": {
            "jsCode": code_node_js.replace('`', '`') # Python f-string handles the backticks fine
        },
        "id": "html_builder",
        "name": "HTML Builder",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": [
             900, 
             450 
        ]
    }

    # Insert Code Node and rewiring
    # Current flow: AI -> Sheets -> Email
    # New flow: AI -> Sheets -> HTML Builder -> Email

    # Update Google Sheets position slightly
    # Update Email Node position slightly
    
    # Let's find nodes
    ai_node = next(n for n in workflow['nodes'] if n['name'] == 'AI Agent - Email Generator')
    sheets_node = next(n for n in workflow['nodes'] if n['name'] == 'Save to Google Sheets')
    email_node = next(n for n in workflow['nodes'] if n['name'] == 'Send Email')
    
    # We want flow: Sheets -> HTML Builder -> Email
    # Sheets is at [900, 300]
    # Email is at [1140, 300]
    
    # Place HTML Builder at [1020, 300]
    code_node['position'] = [1020, 300]
    email_node['position'] = [1240, 300]
    # Shift others if needed? No, Respond to Webhook is at 1380, shift it
    respond_node = next(n for n in workflow['nodes'] if n['name'] == 'Respond to Webhook')
    respond_node['position'] = [1480, 300]

    # Add Code Node
    workflow['nodes'].append(code_node)

    # connections:
    # Remove link from Sheets to Email
    # Add link from Sheets to HTML Builder
    # Add link from HTML Builder to Email
    
    # Sheets -> HTML Builder
    workflow['connections']['Save to Google Sheets']['main'][0][0] = {
        "node": "HTML Builder",
        "type": "main",
        "index": 0
    }
    
    # HTML Builder -> Email
    workflow['connections']['HTML Builder'] = {
        "main": [
            [
                {
                    "node": "Send Email",
                    "type": "main",
                    "index": 0
                }
            ]
        ]
    }
    
    # Update Email Node to use HTML
    email_node['parameters']['emailType'] = 'html'
    email_node['parameters']['message'] = '={{ $json.html }}' # Input from HTML Builder

    save_json(MINDHAFEN_OUT, workflow)
    print(f"MindHafen Saved to {MINDHAFEN_OUT}")

def process_argenterio():
    print("Processing Argenterio...")
    workflow = json.loads(read_file(ARGENTERIO_WORKFLOW))
    html_template = read_file(ARGENTERIO_HTML)
    
    # Teaser Text logic
    # In V7, Teaser is generated by "AI Teaser Generator" -> text (simple string)
    # Link is generated by "Crear Link MP" -> init_point
    
    code_node_js = f"""
    const htmlTemplate = `{html_template}`;
    
    const mp_link = $('Crear Link MP').item.json.init_point || '#';
    const teaser_text = $('AI Teaser Generator').item.json.text || 'Análisis pendiente...';
    const paypal_link = "https://www.paypal.com/ncp/payment/LP2ZBHDAJPLDY"; // Hardcoded in V7
    
    let finalHtml = htmlTemplate.replace('{{{{teaser_text}}}}', teaser_text);
    finalHtml = finalHtml.replace('{{{{payment_link}}}}', mp_link);
    finalHtml = finalHtml.replace('{{{{paypal_link}}}}', paypal_link);
    
    return {{
        json: {{
            html: finalHtml
        }}
    }};
    """
    
    code_node = {
        "parameters": {
            "jsCode": code_node_js
        },
        "id": "html_builder_argt",
        "name": "HTML Builder",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": [
             600, 
             450 
        ]
    }
    
    # Current Flow: Crear Link MP -> Respond (index 0) AND Email (index 1? No, parallel outputs usually same index)
    # V7 connections: Crear Link MP main: [ [Respond], [Email] ] -> Parallel execution
    
    # We want: Crear Link MP -> HTML Builder -> Email
    # Respond node can stay connected to "Crear Link MP" for speed, OR move after HTML Builder.
    # Let's keep Respond connected to MP Link for speed response.
    # But Email path needs to go through HTML Builder.
    
    # "Crear Link MP" connections
    # We remove the connection to "Email - Teaser + Link" 
    # And replace it with "HTML Builder"
    
    workflow['nodes'].append(code_node)
    
    # Find nodes
    mp_node = next(n for n in workflow['nodes'] if n['name'] == 'Crear Link MP')
    email_node = next(n for n in workflow['nodes'] if n['name'] == 'Email - Teaser + Link')
    
    # MP Node Output Connections
    # V7 has:
    # "main": [ [ {node: Respond}, {node: Email} ] ] -> Wait, looking at JSON V7:
    # "Crear Link MP": { "main": [ [ {node: Responder...}, {node: Email...} ] ] }
    # This implies they both run 
    
    # We change it to:
    # "main": [ [ {node: Responder...}, {node: HTML Builder} ] ]
    
    # Find index of Email node in the connection list
    mp_connections = workflow['connections']['Crear Link MP']['main'][0]
    
    # Remove Email node connection
    new_connections = [c for c in mp_connections if c['node'] != 'Email - Teaser + Link']
    
    # Add HTML Builder connection
    new_connections.append({
        "node": "HTML Builder",
        "type": "main",
        "index": 0
    })
    
    workflow['connections']['Crear Link MP']['main'][0] = new_connections
    
    # Connect HTML Builder to Email
    workflow['connections']['HTML Builder'] = {
        "main": [
            [
                {
                    "node": "Email - Teaser + Link",
                    "type": "main",
                    "index": 0
                }
            ]
        ]
    }
    
    # Update Email Node
    # It was hardcoded htmlContent parameter
    # We change htmlContent to expression
    email_node['parameters']['htmlContent'] = '={{ $json.html }}'
    
    # Update generic ID if needed (optional)
    
    save_json(ARGENTERIO_OUT, workflow)
    print(f"Argenterio Saved to {ARGENTERIO_OUT}")

if __name__ == "__main__":
    process_mindhafen()
    process_argenterio()
